# Estimate Neural Manifold Curvature

### Set-up + Imports

In [1]:
import setup

setup.main()
%load_ext autoreload
%autoreload 2
%load_ext jupyter_black

import os

import matplotlib.pyplot as plt
import numpy as np
import torch

os.environ["GEOMSTATS_BACKEND"] = "pytorch"
import geomstats.backend as gs

Working directory:  /home/facosta/neurometry/neurometry
Directory added to path:  /home/facosta/neurometry
Directory added to path:  /home/facosta/neurometry/neurometry


## Load config & model

In [89]:
run_name = "run_6rixqmzt_t2_synthetic_noise_var_1e-05_embedding_dim_3"

In [92]:
results_dir = os.path.join(os.getcwd(), "curvature/results")
models_dir = os.path.join(results_dir, "trained_models")
configs_dir = os.path.join(results_dir, "configs")


import json

model_file = os.path.join(models_dir, f"{run_name}_model.pt")
config_file = os.path.join(configs_dir, f"{run_name}.json")

with open(config_file, "r") as file:
    config_dict = json.load(file)


class Config:
    def __init__(self, config_dict):
        self.__dict__.update(config_dict)

    def __getattr__(self, name):
        if name in self:
            return self[name]
        else:
            raise AttributeError(
                f"'{self.__class__.__name__}' object has no attribute '{name}'"
            )


config = Config(config_dict)

In [94]:
import neurometry.curvature.models.toroidal_vae as toroidal_vae


model = toroidal_vae.ToroidalVAE(
    data_dim=config.data_dim,
    latent_dim=config.latent_dim,
    sftbeta=config.sftbeta,
    encoder_width=config.encoder_width,
    encoder_depth=config.encoder_depth,
    decoder_width=config.decoder_width,
    decoder_depth=config.decoder_depth,
    posterior_type=config.posterior_type,
).to(config.device)


# model.load_state_dict(torch.load(model_file))
# model.eval();

model = torch.load(model_file)
model.eval();

## Compute extrinsic curvature

In [95]:
import neurometry.curvature.evaluate as evaluate

z_grid, geodesic_dist, _, curv_norms_learned = evaluate.compute_curvature_learned(
    model=model,
    config=config,
    embedding_dim=config.embedding_dim,
    n_grid_points=config.n_grid_points,
)

torch.Size([100, 2])
An error occurred for i=0: linalg.inv: The diagonal element 2 is zero, the inversion could not be completed because the input matrix is singular.
tensor([[3.5656, 0.0000],
        [0.0000, 0.0000]])
An error occurred for i=1: linalg.inv: The diagonal element 2 is zero, the inversion could not be completed because the input matrix is singular.
tensor([[3.5656, 0.0000],
        [0.0000, 0.0000]])
An error occurred for i=2: linalg.inv: The diagonal element 2 is zero, the inversion could not be completed because the input matrix is singular.
tensor([[3.5656, 0.0000],
        [0.0000, 0.0000]])
An error occurred for i=3: linalg.inv: The diagonal element 2 is zero, the inversion could not be completed because the input matrix is singular.
tensor([[3.5656, 0.0000],
        [0.0000, 0.0000]])
An error occurred for i=4: linalg.inv: The diagonal element 2 is zero, the inversion could not be completed because the input matrix is singular.
tensor([[3.5656, 0.0000],
        [0.